---

- hosts:
    - all
  become: true
  gather_facts: true

  vars:
    ansible_debug: true
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_pass: builder
    ansible_become_pass: builder

  roles:
    - bootstrap

...